services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      DB_NAME: auth_db
      JWT_SECRET: super-secret-dev-key-change-in-prod
      PORT: 4000
    depends_on:
      - auth-db

  catalog-db:
    image: postgres:16
    container_name: catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    ports:
      - "5434:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      DB_HOST: catalog-db
      DB_PORT: 5432
      DB_USER: catalog_user
      DB_PASSWORD: catalog_pass
      DB_NAME: catalog_db
      ES_NODE: http://elasticsearch:9200
      PORT: 4001
    depends_on:
      - catalog-db
      - elasticsearch

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  cart-service:
    build: ./cart-service
    container_name: cart-service
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      REDIS_URL: redis://redis:6379
      CATALOG_SERVICE_URL: http://catalog-service:4001
      PORT: 4002
    depends_on:
      - redis
      - catalog-service

volumes:
  auth-db-data:
  catalog-db-data:
  es-data:
  redis-data: