apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
stringData:
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: auth_pass
  POSTGRES_DB: auth_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:16
          envFrom:
            - secretRef:
                name: auth-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: auth-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: auth-db-storage
          persistentVolumeClaim:
            claimName: auth-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432