apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: orders_db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-db
  template:
    metadata:
      labels:
        app: orders-db
    spec:
      containers:
        - name: orders-db
          image: postgres:16
          envFrom:
            - secretRef:
                name: orders-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: orders-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: orders-db-storage
          persistentVolumeClaim:
            claimName: orders-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
spec:
  selector:
    app: orders-db
  ports:
    - port: 5432
      targetPort: 5432