apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-db
  template:
    metadata:
      labels:
        app: payments-db
    spec:
      containers:
        - name: payments-db
          image: postgres:16

          envFrom:
            - secretRef:
                name: payments-db-secret

          ports:
            - containerPort: 5432

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: payments-db-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: payments-db-storage
          persistentVolumeClaim:
            claimName: payments-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: payments-db
spec:
  selector:
    app: payments-db
  ports:
    - port: 5432
      targetPort: 5432
