if(process.env.PHASE2_INTEGRATION==='true'){
 const pool=require('../src/db');const fixture=require('../../scripts/phase2/test-support/admin-db')('payments',require('pg'));const {processRequest}=require('../src/paymentStore');
 const payment={eventId:'restricted-payment',operationId:'990001:payment_requested',orderId:990001,userId:22,amount:'20.00'};
 const refund={...payment,eventId:'restricted-refund',operationId:'990001:refund_requested'};
 beforeEach(async()=>{const identity=(await pool.query('SELECT current_user,current_database()')).rows[0];expect(identity.current_user).toBe('payments_app');expect(identity.current_database).toBe('payments_phase2_test');await fixture.query('TRUNCATE payments,refunds,inbox_events,outbox_events RESTART IDENTITY');delete process.env.REFUND_OUTCOME;delete process.env.PAYMENT_OUTCOME;});
 afterAll(()=>Promise.all([pool.end(),fixture.end()]));
 test('restricted payment insertion and duplicate different event identity stay unique',async()=>{await processRequest('payment_requested',payment);await processRequest('payment_requested',{...payment,eventId:'payment-redelivery'});expect((await pool.query('SELECT * FROM payments')).rows).toHaveLength(1);expect((await pool.query('SELECT payload FROM outbox_events LIMIT 1')).rows[0].payload.operationId).toBe(payment.operationId);});
 test('refund insertion, concurrent duplicates and new event IDs cannot duplicate success',async()=>{await processRequest('payment_requested',payment);await Promise.all([processRequest('refund_requested',refund),processRequest('refund_requested',refund)]);await processRequest('refund_requested',{...refund,eventId:'duplicate-refund'});const rows=(await pool.query('SELECT * FROM refunds')).rows;expect(rows).toHaveLength(1);expect(rows[0].status).toBe('refunded');});
 test('failed refund can upsert to succeeded without changing operation ID',async()=>{await processRequest('payment_requested',payment);process.env.REFUND_OUTCOME='failed';await processRequest('refund_requested',refund);delete process.env.REFUND_OUTCOME;await processRequest('refund_requested',{...refund,eventId:'retry-refund'});expect((await pool.query('SELECT status FROM refunds')).rows).toEqual([{status:'refunded'}]);});
 test('database failure rolls back refund, inbox and result; same command retries safely',async()=>{
  await processRequest('payment_requested',payment);const realConnect=pool.connect.bind(pool);let injected=false;
  const spy=jest.spyOn(pool,'connect').mockImplementation(async()=>{const client=await realConnect();const realQuery=client.query.bind(client);client.query=async(sql,...args)=>{if(!injected && sql.startsWith('INSERT INTO outbox_events')){injected=true;return realQuery('SELECT 1/0');}return realQuery(sql,...args);};return client;});
  try{await expect(processRequest('refund_requested',refund)).rejects.toMatchObject({code:'22012'});}finally{spy.mockRestore();}
  expect((await pool.query('SELECT * FROM refunds')).rows).toHaveLength(0);expect((await pool.query('SELECT * FROM inbox_events WHERE event_id=$1',[refund.eventId])).rows).toHaveLength(0);
  await processRequest('refund_requested',refund);expect((await pool.query("SELECT * FROM refunds WHERE status='refunded'")).rows).toHaveLength(1);
 });
 test('conflicting operation identity is rejected before any financial write',async()=>{await expect(processRequest('refund_requested',{...refund,operationId:'wrong-operation'})).rejects.toMatchObject({permanent:true});expect((await pool.query('SELECT * FROM refunds')).rows).toHaveLength(0);});
 test('amount updates remain forbidden while exact upsert columns and sequence are allowed',async()=>{const r=(await pool.query("SELECT has_column_privilege(current_user,'refunds','status','UPDATE') AS status,has_column_privilege(current_user,'refunds','amount','UPDATE') AS amount,has_sequence_privilege(current_user,'refunds_id_seq','USAGE') AS sequence")).rows[0];expect(r).toEqual({status:true,amount:false,sequence:true});});
}else test.skip('Restricted-role integration requires isolated local harness',()=>{});
